const cu1 = require('../images/close ups/babyPinecones042119.jpg');
const cu2 = require('../images/close ups/beaverpondTrail3.jpg');
const cu3 = require('../images/close ups/beaverpondTral5.jpg');
const imageDataCU = [
    {
        id: '1',
        name: 'babyPinecones',
        imageSrc: cu1,
        alt: 'close up of open hand holding a tiny branch of pine cone buds',
    },
    {
        id: '2',
        name: 'beaverpondTrail3',
        imageSrc: cu2,
        alt: 'close up of open bright yellow flower and stamen',
    },
    {
        id: '3',
        name: 'beaverpond trail5',
        imageSrc: cu3,
        alt: 'close up of a brown snail in his shell on a curvy log',
    },
    {
        id: '4',
        name: 'beaverpond trail6',
        imageSrc: './src/images/close-ups/beaverpond-trail6.jpg',
        alt: 'close up of 3 wild blue long stemmed flowers',
    },
    {
        id: '5',
        name: 'beverpond trail7',
        imageSrc: './src//images/close-ups/beaverpond-trail7.jpg',
        alt: 'close up of a green plant with ten long cupped leaves in a star shape holding morning dew drops',
    },
    {
        id: '6',
        name: 'beaverpond trail9',
        imageSrc: './src//images/close-ups/beaverpond-trail9.jpg',
        alt: 'close up of a tiny ladybug on a long spikey leafed plant',
    },
    {
        id: '7',
        name: 'beaverpond trail10',
        imageSrc: './src//images/close-ups/beaverpond-trail10.jpg',
        alt: 'close up of some flower-like green plants on the winter thawed ground',
    },
    {
        id: '8',
        name: 'berries yellowstone 090918',
        imageSrc: './src//images/close-ups/berries-yellowstone-090918.jpg',
        alt: 'close up of a long brown stem of several tiny red berries',
    },
    {
        id: '9',
        name: 'cacti at yellowstone 090918',
        imageSrc: './src//images/close-ups/cacti-at-yellowstone-090918.jpg',
        alt: 'close up of a piece of winter ground covered in asorted sizes of long spiked cacti plants',
    },
    {
        id: '10',
        name: 'feb162018 11',
        imageSrc: './src//images/close-ups/feb132018-11.jpg',
        alt: 'close up of the winter thawed ground displaying the start of green ground cover plants in red mulch bed',
    },
    {
        id: '11',
        name: 'feb162018 12',
        imageSrc: './src//images/close-ups/feb162018-12.jpg',
        alt: 'close up of a striking white snail shell on a dried up winter brown waterway',
    },
    {
        id: '12',
        name: 'feb162018 17',
        imageSrc: './src//images/close-ups/feb162018-17.jpg',
        alt: 'close up of a scattering of dried winter golden brown and red brown leaves with an interesting currosion pattern on the dry brown ground',
    },
    {
        id: '13',
        name: 'feb162018 18',
        imageSrc: './src//images/close-ups/feb162018-18.jpg',
        alt: 'close up of a deep knot in a dried large and mossy barked winter tree',
    },
    {
        id: '14',
        name: 'feb162018 19',
        imageSrc: './src//images/close-ups/feb162018-19.jpg',
        alt: 'close up of a deep fork in a dried large and mossy barked winter tree',
    },
    {
        id: '15',
        name: 'feb162018 22',
        imageSrc: './src//images/close-ups/feb162018-22.jpg',
        alt: 'close up of a white dog walking down a winter thawed sidewalk in the countryside by a large forest of bare trees and a trailer',
    },
    {
        id: '16',
        name: 'feb162018 23',
        imageSrc: './src//images/close-ups/feb162018-23.jpg',
        alt: 'close up of a white opossum laying in the winter dried pile of brown leaves and grass',
    },
    {
        id: '17',
        name: 'forest flower berries yellowstone 091018',
        imageSrc: './src//images/close-ups/forest-flower-berries-yellowstone-091018.jpg',
        alt: 'close up of large yellowed leaves with single red berry in each on the greenish brown ground',
    },
    {
        id: '18',
        name: 'Haceta Head Lighthouse beach 1 041519',
        imageSrc: './src//images/close-ups/Haceta-Head-Lighthouse-beach-1-041519.jpg',
        alt: 'close up of a sandy red brown eroded rock on the light brown beach sand',
    },
    {
        id: '19',
        name: 'Haceta Head Lighthouse beach 2 041519',
        imageSrc: './src//images/close-ups/Haceta-Head-Lighthouse-beach-2-041519.jpg',
        alt: 'close up of an empty white and slightly broken seashell with a beautiful red speckled pattern sitting on a wet packed brown sandy beach ground',
    },
    {
        id: '20',
        name: 'Haceta Head Lighthouse beach 3 041519',
        imageSrc: './src//images/close-ups/Haceta-Head-Lighthouse-beach-3-041519. jpg',
        alt: 'close up of an empty red and slightly broken seashel with a beautiful white marbled pattern sitting on a wet packed brown sandy beach ground',
    },
    {
        id: '21',
        name: 'Haceta Head Lighthouse beach flower 041519',
        imageSrc: './src//images/close-ups/Haceta-Head-Lighthouse-beach-flower-041519.jpg',
        alt: 'close up of a tiy bluish purple 5 petal flower in a bed of wild green leafy vegitation',
    },
    {
        id: '22',
        name: 'Haceta Head Lighthouse beach foliage 041519',
        imageSrc: './src//images/close-ups/Haceta-Head-Lighthouse-beach-foliage-041519.jpg',
        alt: 'close up of a tiny group of 4 long plant stems colored curled and textured like octopus tenticles',
    },
    {
        id: '23',
        name: 'Haceta Head Lighthouse beach tour trail 2 041519',
        imageSrc: './src//images/close-ups/Haceta-Head-Lighthouse-beach-tour-trail-2-041519.jpg',
        alt: 'close up of a patch of thick long yellowgreen moss on a white and brown branch with a blurred morning forest of bare trees in the background',
    },
    {
        id: '24',
        name: 'Laura snow pics in NC 120917 16',
        imageSrc: './src//images/close-ups/Laura-snow-pics-in-NC-120917-16.jpg',
        alt: 'close up of a group of puppy dog foot prints in a muddy clay winter thawed ground with a patch of snow near by',
    },
    {
        id: '25',
        name: 'michels farm 14',
        imageSrc: './src//images/close-ups/michels-farm-14.jpg',
        alt: 'close up of a brown hourse with a white flair and grey bridal looking straight into the camera with the fence and white building n the background',
    },
    {
        id: '26',
        name: 'michels farm21',
        imageSrc: './src//images/close-ups/michels-farm21.jpg',
        alt: 'close up of a tiny bouquet of white wild flowers in a bed of lively green ground foliage',
    },
    {
        id: '27',
        name: 'moss and mushroom bed yellowstone 091018',
        imageSrc: './src//images/close-ups/moss-and-mushroom-bed-yellowstone-091018.jpg',
        alt: 'close up of a large patch of yellowgreen moss scattered with white long stemmed wild mushrooms',
    },
    {
        id: '28',
        name: 'new life beginning yellowstone 091018',
        imageSrc: './src//images/close-ups/new-life-beginning-yellowstone-091018.jpg',
        alt: 'close up of 2 tiny bright green shell shaped leaves growing out from between a group of wet dark grey boulders',
    },
    {
        id: '29',
        name: 'purple daisy yellowstone 090918',
        imageSrc: './src//images/close-ups/purple-daisy-yellowstone-090918.jpg',
        alt: 'close up of a tiny baby purple daisy flower with a yellow stamen sitting in a summer green patch of wild leaves and grass',
    },
    {
        id: '30',
        name: 'rainy stroll 2 on 061818',
        imageSrc: './src//images/close-ups/rainy-stroll-2-on-061818.jpg',
        alt: 'close up of a long stemmed group of wild flowers gradiently colored from white to bright yellow and purple growing out from a wet patch of wild green grassy ground',
    },
    {
        id: '31',
        name: 'rainy stroll 3 on 061818',
        imageSrc: './src//images/close-ups/rainy-stroll-3-on-061818.jpg',
        alt: 'close up of a hand grasping a bouquet of colorful wild flowers including sweet yellow blooms, tiny white breathy stalks, and gradient white to blue bell like blooms',
    },
    {
        id: '32',
        name: 'rainy stroll 4 on 061818',
        imageSrc: './src//images/close-ups/rainy-stroll-4-on-061818.jpg',
        alt: 'close up of the red orange berry clustered branches of a green piny type bush with dark brown stalks',
    },
    {
        id: '33',
        name: 'rainy stroll 5 on 061818',
        imageSrc: './src//images/close-ups/rainy-stroll-5-on-061818.jpg',
        alt: 'close up of a single cluster of red orange berry on the branch of a green piny type bush with a blurred background showing the rest of the bush',
    },
    {
        id: '34',
        name: 'ren faire zoo10',
        imageSrc: './src//images/close-ups/ren-faire-zoo10.jpg',
        alt: 'close up of a white rectangular plate of perfectly cut sushi garnished with a beautiful purple flower with a white middle and purple stamen',
    },
    {
        id: '35',
        name: 'Roastbeef plate at Lamberts 102418',
        imageSrc: './src//images/close-ups/Roastbeef-plate-at-Lamberts-102418.jpg',
        alt: 'close up of a white circular plate with shredded roast beef with brown gravy on top, small white bowl of mashed potatoes, small biege bowl of glazed peaches, plate garnished with an orange slice and a parsley stalk',
    },
    {
        id: '36',
        name: 'tiny waterfall yellowstone 091018',
        imageSrc: './src//images/close-ups/tiny-waterfall-yellowstone-091018.jpg',
        alt: 'close up of lake water spilling through a cluster of rocks onto a shallow portion layer of more rocks',
    },
    {
        id: '37',
        name: 'tree bark yellowstone 091018',
        imageSrc: './src//images/close-ups/tree-bark-yellowstone-091018.jpg',
        alt: 'close up of a fallen tree with white bark and a pattern that seems to look like cave type carvings in it',
    },
    {
        id: '38',
        name: 'Trucking with Uncle Pablo (29) Jan 2018',
        imageSrc: './src//images/close-ups/Trucking-with-Uncle-Pablo-(29)-Jan-2018.jpg',
        alt: 'close up of a light brown leaf with a shear layer of winter frost on it as it sits on the frosted dried winter grasses',
    },
    {
        id: '39',
        name: 'wild berries yellowstone 091018',
        imageSrc: './src//images/close-ups/wild-berries-yellowstone-091018.jpg',
        alt: 'close up of a stalk of red and pink razberry-like wild berries growing out of a randomly scattered patch of leafy greens of all shades and white ground stalks in the dark grey soil',
    },
];

export default imageDataCU;